# Generated by Django 4.2.3 on 2023-08-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreusuario', models.CharField(max_length=40)),
                ('contraseña', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
    ]
