# Generated by Django 4.2.3 on 2023-08-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_alter_usuario_apellido_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombreusuario',
            field=models.CharField(default='', max_length=40),
        ),
    ]
