# Generated by Django 4.2.3 on 2023-08-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_perfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(default='', max_length=200)),
                ('usuarioidemisor', models.IntegerField()),
                ('usuarioidreceptor', models.IntegerField()),
                ('leido', models.BooleanField(default=False)),
            ],
        ),
    ]
