# Generated by Django 4.2.3 on 2023-09-03 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_entradasblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradasblog',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
